_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 55
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 55
                - 103
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.4
            "5": 0.19.11
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
batch_size:
    value: 32
image_size:
    value: 224
learning_rate:
    value: 0.001
num_epochs:
    value: 50
seed:
    value: 42
