defaults:
  - data: butterfly_dataset
  - model: unet_autoencoder
  - training: default
  - _self_

# Configuración global
seed: 42
project_name: "butterfly-transfer-learning"

# Configuración de dispositivo
device:
  auto_detect: true
  precision: "16-mixed"  # Precisión mixta para GPU
  benchmark: true  # Optimizaciones cuDNN

# Configuración de logging
logging:
  use_wandb: true
  log_every_n_steps: 50
  save_dir: "logs"

# Configuración de checkpoints
checkpointing:
  monitor: "val_loss"
  mode: "min"
  save_top_k: 3
  save_last: true 