_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 103
            "3":
                - 2
                - 13
                - 16
                - 55
            "4": 3.12.7
            "5": 0.20.1
            "8":
                - 1
            "12": 0.20.1
            "13": darwin-arm64
batch_size:
    value: 32
image_size:
    value: 224
learning_rate:
    value: 0.001
num_epochs:
    value: 50
seed:
    value: 42
